# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='path',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('container_parser', 'container_parser')], max_length=255, unique=True),
        ),
    ]
