# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 23:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plugins', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Course full description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(verbose_name='Course start date')),
                ('end_date', models.DateField(verbose_name='Course end date')),
                ('privacy', models.IntegerField(choices=[(0, 'Public')], default=0, verbose_name='Course privacy mode')),
                ('limit', models.IntegerField(default=16, verbose_name='Max number of students')),
                ('example_project', models.FileField(blank=True, null=True, upload_to='projects')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_course', to=settings.AUTH_USER_MODEL)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins.Plugin')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='courses.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
