# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(0, 'Preparation'), (1, 'Open'), (2, 'Finished')], default=0),
        ),
    ]
