# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 20:02
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
